function config_graphic_settings(fig)
set(fig, ...
    'DefaultFigureColor', 'w', ...
    'DefaultFigureWindowState', 'maximized', ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', 15, ...
    'DefaultAxesLineWidth', 1.5, ...
    'DefaultLineLineWidth', 3, ...
    'DefaultAxesTitleFontWeight', 'normal', ...
    'DefaultAxesTitleFontSize', 1.2, ...
    'DefaultAxesLabelFontSize', 1.2, ...
    'DefaultAxesTickDirMode', 'manual', ...
    'DefaultAxesTickDir', 'out', ...
    'DefaultAxesBoxMode', 'manual', ...
    'DefaultAxesBox', 'off', ...
    'DefaultLegendLocation', 'best', ...
    'DefaultLegendFontSizeMode', 'auto', ...
    'DefaultLegendBox', 'off');
end